name: Validate Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [dev]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  validate-branch-to-qa-org:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Tooling (Node for CLIs; Java for PMD engine)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install modern Salesforce CLI + scanner (used for scan/validate/test)
      - name: Install Salesforce CLI + Scanner
        run: |
          npm i -g @salesforce/cli
          sf --version
          sf plugins install @salesforce/sfdx-scanner
          sf plugins

      # *** Allowlist unsigned plugins for BOTH sf & sfdx to avoid prompts ***
      - name: Allow unsigned plugins (no prompts in CI)
        run: |
          mkdir -p "$HOME/.config/sf" "$HOME/.config/sfdx"
          printf '["sfdx-git-delta"]\n' > "$HOME/.config/sf/unsignedPluginAllowList.json"
          printf '["sfdx-git-delta"]\n' > "$HOME/.config/sfdx/unsignedPluginAllowList.json"

      # Install legacy SFDX CLI and install sgd there; use `sfdx` to run delta
      - name: Install sfdx + sfdx-git-delta
        run: |
          npm i -g sfdx-cli
          sfdx --version
          sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Populate auth file
        run: echo "${{ secrets.SFDX_QA_URL }}" > ./SFDX_QA_URL.txt

      - name: Authenticate to target SF Org
        run: sf org login sfdx-url -f ./SFDX_QA_URL.txt -a qa

      # Ensure the base branch commit exists locally (needed for diff)
      - name: Fetch base branch
        run: |
          git fetch --no-tags origin ${{ github.event.pull_request.base.ref }} --prune --depth=0
          git rev-parse ${{ github.event.pull_request.base.sha }}

      - name: Create delta packages (PR base ↔ head)
        run: |
          BASE=${{ github.event.pull_request.base.sha }}
          HEAD=${{ github.sha }}
          mkdir -p changed-sources
          # Use the plugin via *sfdx* CLI
          sfdx sgd:source:delta \
            --from "$BASE" \
            --to "$HEAD" \
            --output changed-sources/ \
            --generate-delta \
            --source force-app/

      - name: Detect empty delta
        id: delta
        run: |
          if [ ! -s changed-sources/package/package.xml ] || ! grep -q "<types>" changed-sources/package/package.xml; then
            echo "empty=true" >> $GITHUB_OUTPUT
          else
            echo "empty=false" >> $GITHUB_OUTPUT
          fi

      # Static analysis (matches your ADO job)
      - name: Run PMD + ESLint-LWC
        run: |
          mkdir -p pmd-report lwc-report
          sf scanner run --target "force-app" --engine pmd \
            --outfile "pmd-report/pmd-analysis.csv" --format csv
          sf scanner run --target "force-app/main/default/lwc/**/*" --engine eslint-lwc \
            --outfile "lwc-report/lwc-analysis.csv" --format csv

      - name: Validate delta with tests + reports
        if: steps.delta.outputs.empty == 'false'
        run: |
          sf project deploy validate \
            --manifest "changed-sources/package/package.xml" \
            --target-org qa \
            --test-level RunLocalTests \
            --coverage-formatters cobertura \
            --junit \
            --results-dir coverage

      # If no metadata changed, still produce reports by running tests explicitly
      - name: Fallback: run Apex tests to produce JUnit & Cobertura
        if: steps.delta.outputs.empty == 'true'
        run: |
          mkdir -p coverage
          sf apex run test \
            --test-level RunLocalTests \
            --code-coverage \
            --result-format junit \
            --output-dir coverage \
            --wait 60 \
            --target-org qa || true

      - name: Inspect results (debug)
        if: always()
        run: ls -R coverage || true

      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: PMDAnalysisReport
          path: pmd-report/pmd-analysis.csv

      - name: Upload LWC report
        uses: actions/upload-artifact@v4
        with:
          name: LWCAnalysisReport
          path: lwc-report/lwc-analysis.csv

      - name: Publish JUnit to PR Checks
        if: always() && hashFiles('coverage/junit/*.xml') != ''
        uses: dorny/test-reporter@v1
        with:
          name: Apex Tests
          path: coverage/junit/*.xml
          reporter: java-junit

      - name: Coverage summary (Cobertura → PR summary)
        if: always() && hashFiles('coverage/coverage/cobertura.xml') != ''
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/coverage/cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add coverage to Job Summary
        if: always() && hashFiles('code-coverage-results.md') != ''
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
